name: demo
root: ~/

windows:
  - demo:
      layout: main-vertical
      panes:
        # Ouput ascii art from the received video stream
        - gst-launch-1.0   rtpbin name=rtpbin   udpsrc address=127.0.0.1 port=60000 caps="application/x-rtp, media=audio, encoding-name=OPUS, clock-rate=48000" ! rtpbin.recv_rtp_sink_0   udpsrc address=127.0.0.1 port=60001 caps="application/x-rtcp" ! rtpbin.recv_rtcp_sink_0   udpsrc address=127.0.0.1 port=60002 caps="application/x-rtp, media=video, encoding-name=VP8, clock-rate=90000" ! rtpbin.recv_rtp_sink_1   udpsrc address=127.0.0.1 port=60003 caps="application/x-rtcp" ! rtpbin.recv_rtcp_sink_1   rtpbin. ! rtpvp8depay ! vp8dec ! aasink     rtpbin. ! rtpopusdepay ! queue ! opusdec ! fakesink

        # Run janus-gateway
        - ~/progs/bin/janus -D

        # Run the demo web application, to be accessed from the host's browser
        - env -C ~/janus-rtpforward-plugin/demo npx vite --host
