#!/bin/bash

cd /vagrant

echo '{"CN":"CA","key":{"algo":"rsa","size":2048}}' | \
  cfssl gencert -initca - | \
  cfssljson -bare ca -

echo '{"signing":{"default":{"expiry":"100000h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json

echo '{"CN":"'server'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | \
  cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="localhost,127.0.0.1" - | \
  cfssljson -bare server
