#!/bin/bash

cd ~
git clone https://github.com/michaelfranzl/janus-rtpforward-plugin.git
cd janus-rtpforward-plugin

git reset --hard
git clean -dfx
git checkout master
git pull
git checkout v0.14.1
autoreconf --verbose --force --install
./configure --prefix=/home/vagrant/progs
make
make install  # installs into {prefix}/lib/janus/plugins

# Prepare the demo
cd demo
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
. /home/vagrant/.nvm/nvm.sh
nvm install 20.10.0
npm ci
